import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
delete process.env.DATABASE_URL;delete process.env.VERCEL;
process.env.DATABASE_PATH=join(mkdtempSync(join(tmpdir(),'physio-test-')),'test.sqlite');
const {run,one,all}=await import('../src/lib/db');
const {savePhysioRecord}=await import('../src/lib/physio-domain');
const {getAppData}=await import('../src/lib/data');
const {physioInput,physioLines}=await import('../src/lib/physio');
import type {User} from '../src/lib/types';
for(const [id,role,specialty] of [['p','patient',''],['other','patient',''],['c','practitioner','physiotherapist'],['c2','practitioner','physiotherapist'],['psych','practitioner','psychologist'],['admin','admin','']])await run('INSERT INTO users(id,name,email,password,role,specialty) VALUES (?,?,?,?,?,?)',id,id,id+'@example.test','unused',role,specialty);
const user=async(id:string)=>(await one<User>('SELECT * FROM users WHERE id=?',id))!;
await run("INSERT INTO appointments(id,patient_id,practitioner_id,starts_at,service,amount) VALUES ('a','p','c','2026-10-01T10:00:00.000Z','Physiotherapy session',100000)");
for(const type of ['physiotherapy','chiropractic'])await run('INSERT INTO notes(id,patient_id,practitioner_id,appointment_id,diagnosis,notes,plan,assessment_json,published) VALUES (?,?,?,?,?,?,?,?,?)',type,'p','c','a','summary','complaint','plan',JSON.stringify({type,fields:{evaluationDate:'2026-10-01'},progress:[]}),type==='chiropractic'?1:0);
const plan={assessmentId:'chiropractic',kind:'plan',date:'2026-10-06',goals:'Walk comfortably',interventions:'Exercise',frequency:'Weekly',published:true};
test('physio records preserve draft privacy, require authorized specialty and a released source for sharing',async()=>{
 for(const id of ['p','other','c2','psych','admin'])await assert.rejects(savePhysioRecord(await user(id),plan));
 await assert.rejects(savePhysioRecord(await user('c'),{...plan,assessmentId:'physiotherapy'}));
 await savePhysioRecord(await user('c'),{...plan,assessmentId:'physiotherapy',published:false});
 const planId=await savePhysioRecord(await user('c'),plan);
 await savePhysioRecord(await user('c'),{assessmentId:'chiropractic',kind:'session',date:'2026-10-07',response:'Improving',nextActions:'Continue',pain:0,published:true});
 await savePhysioRecord(await user('c'),{assessmentId:'chiropractic',kind:'discharge',date:'2026-10-08',response:'Goals met',nextActions:'Home programme',published:true});
 const clinical=await getAppData(await user('c')), patient=await getAppData(await user('p'));
 assert.equal(clinical.physioRecords.length,4);assert.equal(patient.physioRecords.length,3);
 assert.equal((await getAppData(await user('other'))).physioRecords.length,0);
 assert.equal((await getAppData(await user('admin'))).physioRecords.length,0);
 assert.equal((await getAppData(await user('c2'))).physioRecords.length,0);
 assert(physioLines(patient.physioRecords.find(r=>r.kind==='session')!).includes('Pain score (0-10): 0'));
 assert.equal((await all('SELECT * FROM audit WHERE entity=?',planId)).length,1);
 assert.equal(clinical.notes.length,2);
});
test('workflow validates required narratives, pain range and follow-up date',()=>{
 assert(!physioInput.safeParse({...plan,goals:''}).success);
 assert(!physioInput.safeParse({...plan,pain:11}).success);
 assert(!physioInput.safeParse({...plan,reviewDate:'2026-10-01'}).success);
 assert(!physioInput.safeParse({...plan,date:'bad'}).success);
});
